spring:
  datasource:
    url: jdbc:mysql://101.35.219.227:3306/ruiyun-hwy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: sc2022_~*
    druid:
      initial-size: 10 #连接池初始化大小
      max-active: 2000 #最大连接数
      min-idle: 10 #最小空闲连接数
      use-unfair-lock: true
      pool-prepared-statements: false
      validation-query: select 1
      test-while-idle: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 16379
    password: $123456$
    timeout: 3000ms
redis:
  database: crawl

rocketmq:
  name-server: 124.223.114.215:9876
  producer:
    group: async_crawl_group
    topic: ASYNC_CRAWL_TOPIC
    send-message-timeout: 3000
    mqMax: 32
  pull: true
  maxCrawlTime: 1800000 #一次爬取最大30分钟
  maxCrawlCount: 3 #一台机器最多执行3个爬取请求,因为每个请求中最多可能有10个网站的爬取线程

executor:
  corePoolSize: 10
  maxPoolSize: 10
  queueCapacity: 9999

mybatis:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    call-setters-on-nulls: true

feign:
  okhttp:
    enabled: true

ribbon:
  ConnectTimeout: 300000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 300000 #服务请求处理超时时间（毫秒）

logging:
  level:
    root: info
    framework: error