server:
  port: 443 # https默认访问端口
  ssl:
    key-store: classpath:server.keystore # 证书存放的位置
    key-alias: tomcat # 证书别名
    key-store-type: JKS # P12证书格式
    key-store-password: 123456

http:
  port: 80